name: peptide
channels:
  - conda-forge
dependencies:
  - fastapi
  - pandas
  - pip
  - pymol-open-source
  - python=3.10
  - pyyaml
  - asyncpg
  - aiohttp
  - pip:
    # - OmegaFold==0.0.0
    - biopython==1.85
    - torch==1.12.0+cu113
    - vina==1.2.7
    - asyncpg>=0.29.0
    - psycopg2-binary>=2.9.9
    - aiohttp>=3.9.0
    - python-dotenv>=1.0.0
    - numpy<2
    - uvicorn>=0.29.0